-- Idempotent by hand, and deliberately so.
--
-- This table was already created in the shared database by this branch's
-- withdrawn 0018 (the admin preview migrates, see .icm/docs/ENV.md), so a plain
-- CREATE TABLE fails here with "relation already exists" while succeeding on a
-- fresh database. `scripts/migrate.mjs` names this exact repair in its own error
-- text: a new migration, past the high-water mark, that no-ops wherever the
-- object is already there. Generated by db:generate, then edited to add the
-- guards — the snapshot it was generated against is untouched, so the next
-- db:generate still diffs cleanly.
CREATE TABLE IF NOT EXISTS "protocol_templates" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"operator_id" uuid NOT NULL,
	"kind" text NOT NULL,
	"name" text NOT NULL,
	"rows" jsonb NOT NULL,
	"shared" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "protocol_templates" ADD CONSTRAINT "protocol_templates_operator_id_operators_id_fk" FOREIGN KEY ("operator_id") REFERENCES "public"."operators"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
	WHEN duplicate_object THEN null;
END $$;
