import type { AuditActionName } from "@remi/services/shared";
import type { Intent } from "@remi/ui/server";

/**
 * How each recorded action reads, and how loudly.
 *
 * A closed map keyed by the service's action vocabulary: adding an action there
 * without adding it here is a type error, which is the point — a journal row
 * rendering as a raw `patient.deleted` is a row nobody reads.
 */

export const actionLabels: Record<AuditActionName, string> = {
  "patient.created": "profil créé",
  "patient.updated": "profil modifié",
  "patient.deleted": "profil supprimé",
  "recommendation.added": "recommandation ajoutée",
  "recommendation.updated": "recommandation modifiée",
  "recommendation.archived": "recommandation archivée",
  "recommendation.restored": "recommandation réactivée",
  "recommendation.deleted": "recommandation supprimée",
  "recommendation.reordered": "recommandations réordonnées",
  "pantry.added": "essentiel ajouté",
  "pantry.updated": "essentiel modifié",
  "pantry.archived": "essentiel archivé",
  "pantry.restored": "essentiel réactivé",
  "pantry.deleted": "essentiel supprimé",
  "pantry.reordered": "essentiels réordonnés",
  "recipe.created": "recette créée",
  "recipe.updated": "recette modifiée",
  "recipe.archived": "recette archivée",
  "recipe.restored": "recette réactivée",
  "recipe.assigned": "recette attribuée",
  "recipe.assignment_updated": "attribution modifiée",
  "recipe.assignment_archived": "attribution archivée",
  "recipe.assignment_restored": "attribution réactivée",
  "recipe.assignment_removed": "attribution supprimée",
  "note.added": "note ajoutée",
  "note.updated": "note modifiée",
  "note.deleted": "note supprimée",
  "anamnesis.updated": "anamnèse modifiée",
  "goal.added": "objectif ajouté",
  "goal.updated": "objectif modifié",
  "goal.archived": "objectif archivé",
  "goal.restored": "objectif réactivé",
  "goal.deleted": "objectif supprimé",
  "goal.reordered": "objectifs réordonnés",
  "goal.checked_in": "point d'étape ajouté",
  "goal.check_in_updated": "point d'étape modifié",
  "goal.check_in_deleted": "point d'étape supprimé",
  "instruction.updated": "consigne modifiée",
  "instruction.cleared": "consigne retirée",
  "share_link.regenerated": "lien patient régénéré",
  "share_link.emailed": "lien patient envoyé",
  "operator.invited": "invitation envoyée",
  "operator.invite_revoked": "invitation retirée",
  "operator.joined": "compte créé",
  "operator.role_changed": "accès modifié",
  "operator.removed": "compte retiré",
  "operator.signed_in": "connexion",
};

/**
 * Only the irreversible and the access-granting carry an intent. Colouring
 * every row is the same as colouring none — the eye needs the deletions and
 * the account changes to be the ones that stand out.
 */
export const actionIntents: Record<AuditActionName, Intent> = {
  "patient.created": "neutral",
  "patient.updated": "neutral",
  "patient.deleted": "error",
  "recommendation.added": "neutral",
  "recommendation.updated": "neutral",
  "recommendation.archived": "neutral",
  "recommendation.restored": "neutral",
  "recommendation.deleted": "error",
  "recommendation.reordered": "neutral",
  "pantry.added": "neutral",
  "pantry.updated": "neutral",
  "pantry.archived": "neutral",
  "pantry.restored": "neutral",
  "pantry.deleted": "error",
  "pantry.reordered": "neutral",
  "recipe.created": "neutral",
  "recipe.updated": "neutral",
  "recipe.archived": "neutral",
  "recipe.restored": "neutral",
  "recipe.assigned": "neutral",
  "recipe.assignment_updated": "neutral",
  "recipe.assignment_archived": "neutral",
  "recipe.assignment_restored": "neutral",
  "recipe.assignment_removed": "error",
  "note.added": "neutral",
  "note.updated": "neutral",
  "note.deleted": "error",
  "anamnesis.updated": "neutral",
  "goal.added": "neutral",
  "goal.updated": "neutral",
  "goal.archived": "neutral",
  "goal.restored": "neutral",
  "goal.deleted": "error",
  "goal.reordered": "neutral",
  "goal.checked_in": "neutral",
  "goal.check_in_updated": "neutral",
  "goal.check_in_deleted": "error",
  "instruction.updated": "neutral",
  "instruction.cleared": "neutral",
  "share_link.regenerated": "warning",
  "share_link.emailed": "info",
  "operator.invited": "info",
  "operator.invite_revoked": "warning",
  "operator.joined": "info",
  "operator.role_changed": "warning",
  "operator.removed": "error",
  "operator.signed_in": "neutral",
};
