import type { AuditActionName } from "@remi/services/shared";
import type { Intent } from "@remi/ui/server";

/**
 * How each recorded action reads, and how loudly.
 *
 * A closed map keyed by the service's action vocabulary: adding an action there
 * without adding it here is a type error, which is the point — a journal row
 * rendering as a raw `patient.deleted` is a row nobody reads.
 */

export const actionLabels: Record<AuditActionName, string> = {
  "patient.created": "profil créé",
  "patient.updated": "profil modifié",
  "patient.deleted": "profil supprimé",
  "recommendation.added": "recommandation ajoutée",
  "recommendation.updated": "recommandation modifiée",
  "recommendation.archived": "recommandation archivée",
  "recommendation.restored": "recommandation réactivée",
  "recommendation.deleted": "recommandation supprimée",
  "recommendation.reordered": "recommandations réordonnées",
  "recommendation.batch_saved": "section recommandations enregistrée",
  "recommendation.checked_in": "point d'étape de la personne suivie",
  "supplement.added": "complément ajouté",
  "supplement.updated": "complément modifié",
  "supplement.archived": "complément archivé",
  "supplement.restored": "complément réactivé",
  "supplement.deleted": "complément supprimé",
  "supplement.reordered": "compléments réordonnés",
  "supplement.batch_saved": "protocole de compléments enregistré",
  "pantry.added": "essentiel ajouté",
  "pantry.updated": "essentiel modifié",
  "pantry.archived": "essentiel archivé",
  "pantry.restored": "essentiel réactivé",
  "pantry.deleted": "essentiel supprimé",
  "pantry.reordered": "essentiels réordonnés",
  "pantry.batch_saved": "liste d'essentiels enregistrée",
  "recipe.created": "recette créée",
  "recipe.updated": "recette modifiée",
  "recipe.archived": "recette archivée",
  "recipe.restored": "recette réactivée",
  "recipe.assigned": "recette attribuée",
  "recipe.created_and_assigned": "recette créée et attribuée",
  "recipe.duplicated_as_variant": "variante créée",
  "recipe.assigned_bulk": "recettes attribuées",
  "recipe.assignment_updated": "attribution modifiée",
  "recipe.assignment_archived": "attribution archivée",
  "recipe.assignment_restored": "attribution réactivée",
  "recipe.assignment_removed": "attribution supprimée",
  "nutrition_rule.created": "règle créée",
  "nutrition_rule.updated": "règle modifiée",
  "nutrition_rule.revised": "nouvelle version de la règle",
  "nutrition_rule.validated": "règle validée",
  "nutrition_rule.archived": "règle archivée",
  "nutrition_rule.restored": "règle réactivée",
  "meal.logged": "repas ajouté",
  "meal.updated": "repas modifié",
  "meal.feedback_written": "retour écrit",
  "meal.feedback_cleared": "retour effacé",
  "meal.archived": "repas archivé",
  "meal.restored": "repas réactivé",
  "meal.deleted": "repas supprimé",
  "observation.added": "observation ajoutée",
  "observation.updated": "observation modifiée",
  "observation.archived": "observation archivée",
  "observation.restored": "observation réactivée",
  "observation.deleted": "observation supprimée",
  "consultation.recorded": "consultation enregistrée",
  "note.added": "note ajoutée",
  "note.updated": "note modifiée",
  "note.deleted": "note supprimée",
  "anamnesis.updated": "anamnèse modifiée",
  "goal.added": "objectif ajouté",
  "goal.updated": "objectif modifié",
  "goal.archived": "objectif archivé",
  "goal.restored": "objectif réactivé",
  "goal.deleted": "objectif supprimé",
  "goal.reordered": "objectifs réordonnés",
  "goal.checked_in": "point d'étape ajouté",
  "goal.check_in_updated": "point d'étape modifié",
  "goal.check_in_deleted": "point d'étape supprimé",
  "instruction.updated": "consigne modifiée",
  "instruction.cleared": "consigne retirée",
  "summary.updated": "résumé modifié",
  "summary.cleared": "résumé retiré",
  "next_consultation_prep.updated": "note de préparation modifiée",
  "share_link.regenerated": "lien patient régénéré",
  "share_link.emailed": "lien patient envoyé",
  "context.exported": "contexte copié",
  "protocol.copied_from_patient": "lignes reprises d'un autre patient",
  "template.saved": "modèle enregistré",
  "template.overwritten": "modèle remplacé",
  "template.renamed": "modèle renommé",
  "template.deleted": "modèle supprimé",
  "template.shared": "modèle partagé",
  "template.unshared": "partage du modèle retiré",
  "operator.invited": "invitation envoyée",
  "operator.invite_revoked": "invitation retirée",
  "operator.joined": "compte créé",
  "operator.role_changed": "accès modifié",
  "operator.removed": "compte retiré",
  "operator.signed_in": "connexion",
};

/**
 * Only the irreversible and the access-granting carry an intent. Colouring
 * every row is the same as colouring none — the eye needs the deletions and
 * the account changes to be the ones that stand out.
 */
export const actionIntents: Record<AuditActionName, Intent> = {
  "patient.created": "neutral",
  "patient.updated": "neutral",
  "patient.deleted": "error",
  "recommendation.added": "neutral",
  "recommendation.updated": "neutral",
  "recommendation.archived": "neutral",
  "recommendation.restored": "neutral",
  "recommendation.deleted": "error",
  "recommendation.reordered": "neutral",
  "recommendation.batch_saved": "neutral",
  "recommendation.checked_in": "neutral",
  "supplement.added": "neutral",
  "supplement.updated": "neutral",
  "supplement.archived": "neutral",
  "supplement.restored": "neutral",
  "supplement.deleted": "error",
  "supplement.reordered": "neutral",
  "supplement.batch_saved": "neutral",
  "pantry.added": "neutral",
  "pantry.updated": "neutral",
  "pantry.archived": "neutral",
  "pantry.restored": "neutral",
  "pantry.deleted": "error",
  "pantry.reordered": "neutral",
  "pantry.batch_saved": "neutral",
  "recipe.created": "neutral",
  "recipe.updated": "neutral",
  "recipe.archived": "neutral",
  "recipe.restored": "neutral",
  "recipe.assigned": "neutral",
  "recipe.created_and_assigned": "neutral",
  "recipe.duplicated_as_variant": "neutral",
  "recipe.assigned_bulk": "neutral",
  "recipe.assignment_updated": "neutral",
  "recipe.assignment_archived": "neutral",
  "recipe.assignment_restored": "neutral",
  "recipe.assignment_removed": "error",
  "nutrition_rule.created": "neutral",
  "nutrition_rule.updated": "neutral",
  "nutrition_rule.revised": "info",
  // The one act that lets a rule reach a prompt — it should stand out in the
  // journal the way a share-link regeneration does.
  "nutrition_rule.validated": "success",
  "nutrition_rule.archived": "warning",
  "nutrition_rule.restored": "neutral",
  "meal.logged": "neutral",
  "meal.updated": "neutral",
  "meal.feedback_written": "neutral",
  "meal.feedback_cleared": "neutral",
  "meal.archived": "neutral",
  "meal.restored": "neutral",
  "meal.deleted": "error",
  "observation.added": "neutral",
  "observation.updated": "neutral",
  "observation.archived": "neutral",
  "observation.restored": "neutral",
  "observation.deleted": "error",
  "consultation.recorded": "neutral",
  "note.added": "neutral",
  "note.updated": "neutral",
  "note.deleted": "error",
  "anamnesis.updated": "neutral",
  "goal.added": "neutral",
  "goal.updated": "neutral",
  "goal.archived": "neutral",
  "goal.restored": "neutral",
  "goal.deleted": "error",
  "goal.reordered": "neutral",
  "goal.checked_in": "neutral",
  "goal.check_in_updated": "neutral",
  "goal.check_in_deleted": "error",
  "instruction.updated": "neutral",
  "instruction.cleared": "neutral",
  "summary.updated": "neutral",
  "summary.cleared": "neutral",
  "next_consultation_prep.updated": "neutral",
  "share_link.regenerated": "warning",
  "share_link.emailed": "info",
  // Health data left the console, pseudonymous but real — worth the eye, not an
  // alarm: it is the operator doing her job with the tool built for it.
  "context.exported": "warning",
  // One patient's rows read into another patient's grid. The same reasoning as
  // the export above: health data crossed records, which is worth the eye even
  // though it is the operator working inside her own console.
  "protocol.copied_from_patient": "warning",
  "template.saved": "neutral",
  "template.overwritten": "neutral",
  "template.renamed": "neutral",
  "template.deleted": "error",
  // A set that was hers alone is now readable by every operator of the console.
  "template.shared": "warning",
  "template.unshared": "info",
  "operator.invited": "info",
  "operator.invite_revoked": "warning",
  "operator.joined": "info",
  "operator.role_changed": "warning",
  "operator.removed": "error",
  "operator.signed_in": "neutral",
};
