import { beforeAll, describe, expect, it } from "vitest";
import {
  normaliseNutritionText,
  nutrientComponentByKey,
} from "../../../shared/nutrition";
import { registerDatabase } from "../../client";
import { ciqualFixture, loadCiqualFixture } from "../../fixtures/ciqual";
import { createMemoryDatabase } from "../../test-helpers";
import {
  getCiqualImport,
  getFood,
  getFoodNutrients,
  listFoodGroups,
  rankFoodsByComponent,
  refreshFoodCatalogue,
  searchFoods,
} from "./index";

/**
 * The query service, against the committed subset of the real Ciqual 2025
 * table, through the in-memory client — no driver, no network.
 *
 * The assertions are written against properties of the data rather than
 * against particular foods, because the subset is regenerated by
 * `pnpm ciqual:fixture` and a test pinned to « sardine, à l'huile » would
 * break the next time the selection rule changes without anything being wrong.
 * What must hold is the contract: ranking is descending, exclusions exclude,
 * and an unmeasured value never ranks.
 */

/**
 * Throws rather than asserting, so a key that stops existing fails here with
 * its own name instead of as a null dereference three tests later.
 */
const componentCodes = (key: string): readonly string[] => {
  const component = nutrientComponentByKey(key);
  if (!component) {
    throw new Error(`no component "${key}" in the recommendation map`);
  }
  return component.codes;
};

const proteinCode = componentCodes("protein")[0];

beforeAll(async () => {
  const client = createMemoryDatabase();
  registerDatabase(client);
  await loadCiqualFixture(client);
  refreshFoodCatalogue();
});

describe("the committed subset", () => {
  it("is real CIQUAL data, and says which edition", async () => {
    expect(ciqualFixture.edition).toBe("Ciqual 2025");
    expect(ciqualFixture.source.doi).toBe("10.57745/RDMHWY");
    expect(ciqualFixture.source.licence).toContain("Etalab");
  });

  it("spans every named group of the table, so a ranking is not one aisle", async () => {
    const groups = await listFoodGroups();
    expect(groups.length).toBe(11);
    for (const group of groups) {
      expect(group.nameFr).not.toBe("");
      expect(group.code).not.toBe("00");
    }
  });

  it("keeps the export's one ungrouped food, without inventing a group for it", async () => {
    // CIQUAL 2025 ships 24999 « Dessert (aliment moyen) » under group `00`,
    // which its own group file never defines. It stays searchable; it just has
    // no filter row, because the source gives it no name.
    const orphan = ciqualFixture.foods.find((food) => food.groupCode === "00");
    expect(orphan?.groupNameFr).toBe("");
    if (!orphan) {
      throw new Error("the subset no longer carries the ungrouped food");
    }

    const found = await searchFoods({ query: orphan.nameFr });
    expect(found.map((food) => food.code)).toContain(orphan.code);
  });

  it("records the import it came from", async () => {
    const record = await getCiqualImport();
    expect(record?.edition).toBe("Ciqual 2025");
    expect(record?.foodCount).toBe(ciqualFixture.foods.length);
    expect(record?.nutrientCount).toBeGreaterThan(0);
  });
});

describe("searching by name", () => {
  it("finds a food by a fragment of its name", async () => {
    const target = ciqualFixture.foods[0];
    const fragment = target.nameFr.split(",")[0];
    const found = await searchFoods({ query: fragment });
    expect(found.map((food) => food.code)).toContain(target.code);
  });

  it("ignores accents and case — « magnesium » would find « Magnésium »", async () => {
    // Picked from the fixture rather than hard-coded, so the test survives a
    // regenerated subset: any food whose name carries an accent will do.
    const accented = ciqualFixture.foods.find(
      (food) =>
        normaliseNutritionText(food.nameFr) !== food.nameFr.toLowerCase(),
    );
    if (!accented) {
      throw new Error("the subset carries no accented name to search for");
    }

    const term = normaliseNutritionText(accented.nameFr).split(",")[0];
    const found = await searchFoods({ query: term.toUpperCase() });
    expect(found.map((food) => food.code)).toContain(accented.code);
  });

  it("returns nothing for a name no food carries", async () => {
    expect(await searchFoods({ query: "zzzzz-pas-un-aliment" })).toEqual([]);
  });

  it("restricts to a group when asked", async () => {
    const groups = await listFoodGroups();
    const found = await searchFoods({ group: groups[0].code, limit: 500 });
    expect(found.length).toBeGreaterThan(0);
    for (const food of found) {
      expect(food.groupCode).toBe(groups[0].code);
    }
  });

  it("lists every food when the query is empty", async () => {
    const all = await searchFoods({ limit: 500 });
    expect(all).toHaveLength(ciqualFixture.foods.length);
  });
});

describe("one food's composition", () => {
  it("returns its components with names, units, markers and confidence", async () => {
    const target = ciqualFixture.foods[0];
    const rows = await getFoodNutrients(target.code);

    expect(rows.length).toBe(Object.keys(target.nutrients).length);
    for (const row of rows) {
      expect(row.foodCode).toBe(target.code);
      expect(["exact", "traces", "less_than", "not_determined"]).toContain(
        row.marker,
      );
      expect(["A", "B", "C", "D", ""]).toContain(row.confidence);
    }
  });

  it("keeps every confidence code CIQUAL publishes", async () => {
    const rows = await getFoodNutrients(ciqualFixture.foods[0].code);
    const graded = rows.filter((row) => row.confidence !== "");
    expect(graded.length).toBeGreaterThan(0);
    for (const row of graded) {
      expect(["A", "B", "C", "D"]).toContain(row.confidence);
    }
  });

  it("gives nothing back for a code no food carries", async () => {
    expect(await getFoodNutrients("no-such-code")).toEqual([]);
    expect((await getFood("no-such-code")).ok).toBe(false);
  });

  it("finds a food by its CIQUAL code", async () => {
    const result = await getFood(ciqualFixture.foods[0].code);
    expect(result.ok).toBe(true);
  });
});

describe("ranking by a component", () => {
  it("orders foods by the component, richest first", async () => {
    const ranked = await rankFoodsByComponent({
      componentCode: proteinCode,
      limit: 25,
    });
    expect(ranked.length).toBeGreaterThan(1);

    const values = ranked.map((entry) => entry.nutrient.value ?? 0);
    expect([...values].sort((a, b) => b - a)).toEqual(values);
    for (const entry of ranked) {
      expect(entry.nutrient.componentCode).toBe(proteinCode);
      expect(entry.food.code).toBe(entry.nutrient.foodCode);
    }
  });

  it("never ranks a value nobody measured", async () => {
    const ranked = await rankFoodsByComponent({
      componentCode: proteinCode,
      limit: 500,
    });
    for (const entry of ranked) {
      expect(entry.nutrient.marker).toBe("exact");
      expect(entry.nutrient.value).not.toBeNull();
    }
  });

  it("admits traces and upper bounds only when asked", async () => {
    const strict = await rankFoodsByComponent({
      componentCode: proteinCode,
      limit: 500,
    });
    const loose = await rankFoodsByComponent({
      componentCode: proteinCode,
      includeUncertain: true,
      limit: 500,
    });
    expect(loose.length).toBeGreaterThanOrEqual(strict.length);
    for (const entry of loose) {
      expect(entry.nutrient.marker).not.toBe("not_determined");
    }
  });

  it("leaves out the foods the profile rules out", async () => {
    const ranked = await rankFoodsByComponent({
      componentCode: proteinCode,
      limit: 10,
    });
    const excluded = ranked[0].food.code;

    const after = await rankFoodsByComponent({
      componentCode: proteinCode,
      excludeCodes: [excluded],
      limit: 10,
    });
    expect(after.map((entry) => entry.food.code)).not.toContain(excluded);
  });

  it("leaves out whole groups — « pas d'alcool », « pas de laitages »", async () => {
    const ranked = await rankFoodsByComponent({
      componentCode: proteinCode,
      limit: 500,
    });
    const group = ranked[0].food.groupCode;

    const after = await rankFoodsByComponent({
      componentCode: proteinCode,
      excludeGroups: [group],
      limit: 500,
    });
    for (const entry of after) {
      expect(entry.food.groupCode).not.toBe(group);
    }
    expect(after.length).toBeLessThan(ranked.length);
  });

  it("ranks within one group when the recipe wants an ingredient of a kind", async () => {
    const groups = await listFoodGroups();
    const ranked = await rankFoodsByComponent({
      componentCode: proteinCode,
      group: groups[0].code,
      limit: 500,
    });
    for (const entry of ranked) {
      expect(entry.food.groupCode).toBe(groups[0].code);
    }
  });

  it("gives nothing back for a component the table does not carry", async () => {
    expect(await rankFoodsByComponent({ componentCode: "999999" })).toEqual([]);
  });

  it("honours the limit", async () => {
    const ranked = await rankFoodsByComponent({
      componentCode: proteinCode,
      limit: 3,
    });
    expect(ranked).toHaveLength(3);
  });
});

describe("the recommendation map meets the table", () => {
  it("ranks on every component the map names", async () => {
    // The point of the map is that « augmenter le magnésium » becomes a query.
    // A code in it that the table does not answer is a dead entry.
    const answered = await Promise.all(
      ["protein", "fibre", "magnesium", "iron", "calcium"].map(async (key) => {
        const ranked = await rankFoodsByComponent({
          componentCode: componentCodes(key)[0],
          limit: 5,
        });
        return { key, count: ranked.length };
      }),
    );
    for (const entry of answered) {
      expect(entry.count).toBeGreaterThan(0);
    }
  });
});
